### ISSUE TITLE
swapping videos doesnt clear out old caption data

### ISSUE THREAD

**Issue by lmckeen** [SmithAF/ext-video#1]
swap from the default video of 
"https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd"

and then play this video
"https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8"

take a look at the enabled captions and you will notice that the old captions will still appear in the list

**Comment by SmithAF** [comment]
Closed Captions/Text Tracks can not be removed from the video element if they are not from the dom without creating a new video element. This is how normal video elements work. Not an issue.
